#
# Duy Nguyen - duy@cs.brown.edu
#     Date  : May 18, 2011
#

TOPDIR=../..

SRCS=BilinearMapKey.cpp BilinearMapAccumulator.cpp OraclePrimeRep.cpp \
     PrimeRepGenerator.cpp RSAKey.cpp RSAAccumulator.cpp \
     

OBJS=$(SRCS:.cpp=.o)

include ../rule.mk

BilinearMapKey.o: BilinearMapKey.cpp
BilinearMapAccumulator.o: BilinearMapAccumulator.cpp
OraclePrimeRep.o: OraclePrimeRep.cpp
PrimeRepGenerator.o: PrimeRepGenerator.cpp
RSAKey.o: RSAKey.cpp
RSAAccumulator.o: RSAAccumulator.cpp
