#
# Edward Tremel - etremel@cs.brown.edu
# Date: April 19, 2013
# 

TOPDIR=../..

SRCS=BigInt.cpp BigMod.cpp ModPolynomial.cpp Random.cpp

OBJS=$(SRCS:.cpp=.o)

include ../rule.mk

BigInt.o: BigInt.cpp
BigMod.o: BigMod.cpp
ModPolynomial.o: ModPolynomial.cpp
Random.o: Random.cpp
