#
# Duy Nguyen - duy@cs.brown.edu
#     Date  : May 18, 2011
#

TOPDIR=../..

SRCS=LibConversions.cpp Profiler.cpp SHA256.cpp MerkleTree.cpp ThreadPool.cpp

OBJS=$(SRCS:.cpp=.o)

include ../rule.mk

LibConversions.o: LibConversions.cpp
Profiler.o: Profiler.cpp
SHA256.o: SHA256.cpp
MerkleTree.o: MerkleTree.cpp
ThreadPool.o: ThreadPool.cpp
