#
# Duy Nguyen - duy@cs.brown.edu
#     Date  : May 18, 2011
#

TOPDIR=../..

SRCS=Scalar.cpp Scalar_DCLXVI.cpp G.cpp G1_DCLXVI.cpp G2_DCLXVI.cpp GT.cpp GT_DCLXVI.cpp

OBJS=$(SRCS:.cpp=.o)

include ../rule.mk

Scalar.o: Scalar.cpp
Scalar_DCLXVI.o: Scalar_DCLXVI.cpp
G.o: G.cpp
G1_DCLXVI.o: G1_DCLXVI.cpp
G2_DCLXVI.o: G2_DCLXVI.cpp
GT.o: GT.cpp
GT_DCLXVI.o: GT_DCLXVI.cpp
